<?php

namespace App\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;

class AiGenerateController extends Controller
{
    public function pdf(Request $request)
    {
        $request->validate([
            'title' => ['required', 'string', 'max:150'],
            'content' => ['required', 'string'],
        ]);

        $title = $request->title;
        $content = $request->content;

        $pdf = Pdf::loadView('generated.pdf-template', [
            'title' => $title,
            'content' => $content,
        ])->setPaper('a4', 'portrait');

        $fileName = 'generated/' . Str::slug($title) . '-' . time() . '.pdf';

        Storage::disk('public')->put($fileName, $pdf->output());

        return response()->json([
            'success' => true,
            'message' => 'PDF berhasil dibuat.',
            'file_type' => 'pdf',
            'file_name' => basename($fileName),
            'url' => asset('storage/' . $fileName),
        ]);
    }

    public function word(Request $request)
    {
        $request->validate([
            'title' => ['required', 'string', 'max:150'],
            'content' => ['required', 'string'],
        ]);

        $title = $request->title;
        $content = $request->content;

        $phpWord = new PhpWord();

        $phpWord->setDefaultFontName('Calibri');
        $phpWord->setDefaultFontSize(12);

        $section = $phpWord->addSection([
            'marginTop' => 1200,
            'marginRight' => 1000,
            'marginBottom' => 1200,
            'marginLeft' => 1000,
        ]);

        $section->addText('Lunox AI Document', [
            'bold' => true,
            'size' => 10,
            'color' => '2563EB',
        ]);

        $section->addTextBreak(1);

        $section->addText($title, [
            'bold' => true,
            'size' => 20,
            'color' => '111827',
        ]);

        $section->addTextBreak(1);

        $section->addText('Dibuat otomatis oleh Lunox AI', [
            'italic' => true,
            'size' => 10,
            'color' => '6B7280',
        ]);

        $section->addTextBreak(2);

        $paragraphs = preg_split("/\r\n|\n|\r/", $content);

        foreach ($paragraphs as $paragraph) {
            $paragraph = trim($paragraph);

            if ($paragraph === '') {
                $section->addTextBreak(1);
                continue;
            }

            $section->addText($paragraph, [
                'size' => 12,
                'color' => '111827',
            ], [
                'spaceAfter' => 220,
                'lineHeight' => 1.35,
            ]);
        }

        $section->addTextBreak(2);

        $section->addText('Generated by Lunox AI', [
            'italic' => true,
            'size' => 9,
            'color' => '9CA3AF',
        ]);

        $fileName = 'generated/' . Str::slug($title) . '-' . time() . '.docx';
        $path = storage_path('app/public/' . $fileName);

        if (!is_dir(dirname($path))) {
            mkdir(dirname($path), 0777, true);
        }

        $writer = IOFactory::createWriter($phpWord, 'Word2007');
        $writer->save($path);

        return response()->json([
            'success' => true,
            'message' => 'Word berhasil dibuat.',
            'file_type' => 'word',
            'file_name' => basename($fileName),
            'url' => asset('storage/' . $fileName),
        ]);
    }

    public function image(Request $request)
    {
        $request->validate([
            'prompt' => ['required', 'string', 'max:1000'],
        ]);

        return response()->json([
            'success' => false,
            'message' => 'Fitur generate gambar belum dihubungkan ke API image generator. Gunakan OpenAI Images, Replicate, Stability AI, atau Leonardo AI.',
        ], 501);
    }
}
